name: deploy-dev
run-name: Deploy dev
on: [push]
jobs:
  connect-ssh:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
      - name: Read deployment.sh
        id: deployment
        uses: juliangruber/read-file-action@v1
        with:
          path: "deployment.sh"
      - name: Create SSH key + run
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cat ${{ steps.deployment.outputs.content }} | ssh -i $SSH_KEY_PATH app@$SSH_KNOWN_HOSTS
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
