name: deploy-dev
run-name: Deploy dev
on:
  push:
    branches:
      - main
jobs:
  connect-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Read deployment.sh
        id: deployment
        uses: juliangruber/read-file-action@v1
        with:
          path: "deployment.sh"
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: app
          script: ${{ steps.deployment.outputs.content }}
